batch_size: 32
hyperparams:
  lr:
    tunable: true
    default: 1.0e-3
    max_val: 10
    min_val: 1.0e-05
    num_samples: 36
    scale: log10
    dtype: float
  momentum:
    tunable: false
    default: 0.0
    max_val: 0.0
    min_val: 0.0
    num_samples: 1
    scale: linear
    dtype: float
  delay:
    tunable: false
    delay_type: undelayed
    max_L: 0
    dtype: dict
num_epochs: 1
optimizer: adam
testproblem: mnist_2c2d
verbose: true

